// Generated by CoffeeScript 1.6.2
(function() {
  var Landing;

  Landing = (function() {
    var afterCatchDom, catchDom, configValidate, dom, events, functions, initialize, st, suscribeEvents;

    dom = {};
    st = {
      frmRegisterSuscri: '#frmValidate',
      sbmSend: '#sbmSend'
    };
    catchDom = function() {
      dom.frmRegisterSuscri = $(st.frmRegisterSuscri);
      dom.sbmSend = $(st.sbmSend);
    };
    suscribeEvents = function() {
      dom.frmRegisterSuscri.validate(configValidate);
      dom.sbmSend.on('click', events.verifyValid);
    };
    events = {
      verifyValid: function(e) {
        e.preventDefault();
        if (dom.frmRegisterSuscri.valid()) {
          
        } //valid
      }
    };
    configValidate = {
      rules: {
        txtName: {
          required: true,
          nombre: true,
          maxlength: 70
        },
        txtLastName: {
          required: true,
          nombre: true,
          maxlength: 70
        },
        txtEmail: {
          required: true,
          email: true,
          maxlength: 70
        },
        txtDni: {
          required: true,
          dni: true,
          maxlength: 70
        }
      },
      messages: {
        txtName: {
          required: "Este campo es necesario."
        },
        txtLastName: {
          required: "Este campo es necesario."
        },
        txtEmail: {
          required: "Este campo es necesario.",
          email: "Por favor ingrese un correo electrónico válido."
        },
        txtDni: {
          required: "Este campo es necesario."
        }
      }
    };
    initialize = function(oP) {
      $.extend(st, oP);
      catchDom();
      suscribeEvents();
    };
    return {
      init: initialize
    };
  })();

  $(document).on('ready', function() {
    return Landing.init();
  });

}).call(this);
